version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/exam_project2"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/kulturkampf_site"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
